[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = bad user
   vfs objects = full_audit
   full_audit:prefix = %t|%u|%I|%m
   full_audit:success = mkdir rename unlink pwrite open
   full_audit:failure = connect open
   full_audit:facility = local7
   full_audit:priority = notice

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = no
   valid users = @staff, @readonly
   write list = @staff

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = no
   valid users = @staff, @readonly
   write list = @staff

[sourcecode]
   path = /libraryit/sourcecode
   browseable = yes
   read only = no
   valid users = @staff
   invalid users = @readonly

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes
   valid users = @staff, @readonly
   write list = librarian
